version: "3.9"

services:
  postgres-auth-service:
    image: postgres:16
    container_name: postgres-auth-service
    environment:
      POSTGRES_USER: ${DB_USER_AUTH_SERVICE}
      POSTGRES_PASSWORD: ${DB_PASSWORD_AUTH_SERVICE}
      POSTGRES_DB: ${DB_NAME_AUTH_SERVICE}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "${AUTH_SERVICE_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - postgres-auth-service
    restart: always

  match-service:
    build:
      context: ./match-service
      dockerfile: Dockerfile
    container_name: match_service
    ports:
      - "${MATCH_SERVICE_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - postgres-match-service
    restart: always

  postgres-match-service:
    image: postgres:16
    container_name: postgres-match-service
    environment:
      POSTGRES_USER: ${DB_USER_MATCH_SERVICE}
      POSTGRES_PASSWORD: ${DB_PASSWORD_MATCH_SERVICE}
      POSTGRES_DB: ${DB_NAME_MATCH_SERVICE}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

      
volumes:
  postgres_data:
